# Generated by Django 5.2.9 on 2025-12-12 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Broker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique broker code",
                        max_length=50,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                ("name", models.CharField(help_text="Broker name", max_length=200)),
                (
                    "full_name",
                    models.CharField(
                        blank=True, help_text="Full legal name", max_length=300
                    ),
                ),
                (
                    "broker_type",
                    models.CharField(
                        choices=[
                            ("FULL_SERVICE", "Full Service"),
                            ("DISCOUNT", "Discount"),
                            ("DIRECT_MARKET_ACCESS", "Direct Market Access"),
                            ("INSTITUTIONAL", "Institutional"),
                        ],
                        default="FULL_SERVICE",
                        max_length=50,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                (
                    "country",
                    models.CharField(blank=True, default="India", max_length=100),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Registration/License number",
                        max_length=100,
                    ),
                ),
                (
                    "sebi_registration",
                    models.CharField(
                        blank=True, help_text="SEBI registration number", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_preferred",
                    models.BooleanField(default=False, help_text="Preferred broker"),
                ),
                ("source_system", models.CharField(blank=True, max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=100)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Broker",
                "verbose_name_plural": "Brokers",
                "db_table": "broker",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 4217 currency code (e.g., 'USD', 'EUR', 'INR')",
                        max_length=3,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Must be 3 uppercase letters"
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(help_text="Currency name", max_length=100)),
                (
                    "symbol",
                    models.CharField(
                        blank=True,
                        help_text="Currency symbol (e.g., '$', '€', '₹')",
                        max_length=10,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Primary country", max_length=100
                    ),
                ),
                (
                    "decimal_places",
                    models.IntegerField(
                        default=2, help_text="Number of decimal places"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this currency is active"
                    ),
                ),
                (
                    "is_base_currency",
                    models.BooleanField(
                        default=False, help_text="Whether this is the base currency"
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        blank=True, help_text="Source system for ETL", max_length=50
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True, help_text="ID in source system", max_length=100
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, help_text="Last ETL sync timestamp", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "db_table": "currency",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        help_text="Unique client identifier",
                        max_length=50,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("CORPORATE", "Corporate"),
                            ("HNI", "High Net Worth Individual"),
                            ("INSTITUTIONAL", "Institutional"),
                            ("PROPRIETARY", "Proprietary"),
                        ],
                        default="INDIVIDUAL",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(help_text="Client name", max_length=300)),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, help_text="Legal/registered name", max_length=300
                    ),
                ),
                ("short_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                (
                    "country",
                    models.CharField(blank=True, default="India", max_length=100),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "pan_number",
                    models.CharField(blank=True, help_text="PAN number", max_length=10),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, help_text="Tax identification number", max_length=50
                    ),
                ),
                ("account_number", models.CharField(blank=True, max_length=50)),
                (
                    "demat_account",
                    models.CharField(
                        blank=True, help_text="Demat account number", max_length=50
                    ),
                ),
                ("trading_account", models.CharField(blank=True, max_length=50)),
                ("relationship_manager", models.CharField(blank=True, max_length=200)),
                ("account_opening_date", models.DateField(blank=True, null=True)),
                ("account_closing_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended"),
                            ("CLOSED", "Closed"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "risk_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("source_system", models.CharField(blank=True, max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=100)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "client",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["client_id"], name="client_client__54da13_idx"
                    ),
                    models.Index(
                        fields=["client_type", "status"],
                        name="client_client__ebe60d_idx",
                    ),
                    models.Index(
                        fields=["pan_number"], name="client_pan_num_008867_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TradingCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, help_text="Calendar date")),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("NSE", "National Stock Exchange"),
                            ("BSE", "Bombay Stock Exchange"),
                            ("NYSE", "New York Stock Exchange"),
                            ("NASDAQ", "NASDAQ"),
                            ("LSE", "London Stock Exchange"),
                        ],
                        default="NSE",
                        help_text="Exchange name",
                        max_length=50,
                    ),
                ),
                (
                    "is_trading_day",
                    models.BooleanField(
                        default=True, help_text="Whether trading occurs"
                    ),
                ),
                (
                    "is_settlement_day",
                    models.BooleanField(
                        default=True, help_text="Whether settlement occurs"
                    ),
                ),
                (
                    "is_holiday",
                    models.BooleanField(
                        default=False, help_text="Whether it's a holiday"
                    ),
                ),
                (
                    "holiday_name",
                    models.CharField(
                        blank=True, help_text="Name of holiday", max_length=200
                    ),
                ),
                (
                    "holiday_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PUBLIC", "Public Holiday"),
                            ("TRADING", "Trading Holiday"),
                            ("SETTLEMENT", "Settlement Holiday"),
                        ],
                        max_length=50,
                    ),
                ),
                ("market_open_time", models.TimeField(blank=True, null=True)),
                ("market_close_time", models.TimeField(blank=True, null=True)),
                ("is_half_day", models.BooleanField(default=False)),
                ("source_system", models.CharField(blank=True, max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=100)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Trading Calendar",
                "verbose_name_plural": "Trading Calendars",
                "db_table": "trading_calendar",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["date", "exchange", "is_trading_day"],
                        name="trading_cal_date_4daaa0_idx",
                    )
                ],
                "unique_together": {("date", "exchange")},
            },
        ),
    ]
