# Generated by Django 5.2.9 on 2025-12-12 22:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reference_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Stock symbol/ticker", max_length=50, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Company/Security name", max_length=200),
                ),
                (
                    "isin",
                    models.CharField(blank=True, help_text="ISIN code", max_length=12),
                ),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("NSE", "National Stock Exchange"),
                            ("BSE", "Bombay Stock Exchange"),
                            ("NYSE", "New York Stock Exchange"),
                            ("NASDAQ", "NASDAQ"),
                            ("LSE", "London Stock Exchange"),
                        ],
                        default="NSE",
                        max_length=50,
                    ),
                ),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("EQUITY", "Equity"),
                            ("DEBT", "Debt"),
                            ("DERIVATIVE", "Derivative"),
                            ("COMMODITY", "Commodity"),
                            ("CURRENCY", "Currency"),
                        ],
                        default="EQUITY",
                        max_length=50,
                    ),
                ),
                ("sector", models.CharField(blank=True, max_length=100)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "lot_size",
                    models.IntegerField(
                        default=1, help_text="Minimum trading lot size"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "stock",
                "ordering": ["symbol"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "exchange"], name="stock_symbol_c37a64_idx"
                    ),
                    models.Index(
                        fields=["asset_class", "is_active"],
                        name="stock_asset_c_d9146f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=10
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("MARKET", "Market Order"),
                            ("LIMIT", "Limit Order"),
                            ("STOP_LOSS", "Stop Loss"),
                            ("STOP_LOSS_LIMIT", "Stop Loss Limit"),
                        ],
                        default="MARKET",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price for LIMIT orders",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "stop_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Trigger price for STOP orders",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("filled_quantity", models.IntegerField(default=0)),
                (
                    "average_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SUBMITTED", "Submitted to Exchange"),
                            ("PARTIALLY_FILLED", "Partially Filled"),
                            ("FILLED", "Filled"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "created_by_name",
                    models.CharField(
                        editable=False,
                        help_text="Real name of maker (auto-filled)",
                        max_length=300,
                    ),
                ),
                (
                    "created_by_employee_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Employee ID of maker",
                        max_length=50,
                    ),
                ),
                (
                    "approved_by_name",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Real name of checker (auto-filled)",
                        max_length=300,
                    ),
                ),
                (
                    "approved_by_employee_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Employee ID of checker",
                        max_length=50,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "validity",
                    models.CharField(
                        choices=[
                            ("DAY", "Day Order"),
                            ("IOC", "Immediate or Cancel"),
                            ("GTC", "Good Till Cancelled"),
                        ],
                        default="DAY",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Checker - User who approved/rejected this order",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "broker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="reference_data.broker",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="reference_data.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Maker - User who created this order",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="orders.stock",
                    ),
                ),
            ],
            options={
                "db_table": "order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trade_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=10
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("exchange_trade_id", models.CharField(blank=True, max_length=100)),
                (
                    "executed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "executed_by_name",
                    models.CharField(
                        editable=False,
                        help_text="Name of person who executed (from order maker)",
                        max_length=300,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trades",
                        to="orders.order",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trades",
                        to="orders.stock",
                    ),
                ),
            ],
            options={
                "db_table": "trade",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["-created_at", "status"], name="order_created_089a56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_by", "status"], name="order_created_746534_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["stock", "-created_at"], name="order_stock_i_b9033d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["-executed_at"], name="trade_execute_c79930_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["order", "-executed_at"], name="trade_order_i_b6e687_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["stock", "-executed_at"], name="trade_stock_i_a1ddf4_idx"
            ),
        ),
    ]
