# Generated by Django 5.2.9 on 2025-12-12 14:53

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for role (e.g., 'PORTFOLIO_MANAGER')",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z_]+$",
                                "Only uppercase letters and underscores allowed",
                            )
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the role", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of this role's responsibilities",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this role is active"
                    ),
                ),
                (
                    "is_system_role",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a system-defined role (cannot be deleted)",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order for displaying in lists"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "role",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="User's email address", max_length=254, unique=True
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="User's first name",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="User's last name",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, help_text="User's middle name", max_length=100
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated full name",
                        max_length=300,
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique employee identifier",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, help_text="Department name", max_length=100
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True, help_text="Job title/designation", max_length=100
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?1?\\d{9,15}$", "Enter a valid phone number"
                            )
                        ],
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True,
                        help_text="Mobile phone number",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?1?\\d{9,15}$", "Enter a valid mobile number"
                            )
                        ],
                    ),
                ),
                (
                    "alternate_email",
                    models.EmailField(
                        blank=True, help_text="Alternate email address", max_length=254
                    ),
                ),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                (
                    "country",
                    models.CharField(blank=True, default="India", max_length=100),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "joining_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of joining the organization",
                        null=True,
                    ),
                ),
                (
                    "leaving_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of leaving the organization",
                        null=True,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ON_LEAVE", "On Leave"),
                            ("SUSPENDED", "Suspended"),
                            ("TERMINATED", "Terminated"),
                            ("RESIGNED", "Resigned"),
                        ],
                        default="ACTIVE",
                        help_text="Current employment status",
                        max_length=20,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="User profile picture",
                        null=True,
                        upload_to="profiles/",
                    ),
                ),
                ("bio", models.TextField(blank=True, help_text="Short biography")),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", help_text="User's timezone", max_length=50
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("hi", "Hindi")],
                        default="en",
                        help_text="Preferred language",
                        max_length=10,
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of last login", null=True
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.IntegerField(
                        default=0,
                        help_text="Number of consecutive failed login attempts",
                    ),
                ),
                (
                    "account_locked_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Account locked until this timestamp",
                        null=True,
                    ),
                ),
                (
                    "password_changed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When password was last changed",
                        null=True,
                    ),
                ),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=False,
                        help_text="User must change password on next login",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional user metadata as JSON",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "reporting_manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Direct reporting manager",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "user",
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for permission (e.g., 'view_customer_data')",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z_]+$",
                                "Only lowercase letters and underscores allowed",
                            )
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the permission", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what this permission allows",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Permission category (e.g., 'orders', 'portfolio', 'reports')",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this permission is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "permission",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="permission_categor_c0113e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.CharField(
                        blank=True,
                        help_text="User who granted this permission",
                        max_length=200,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about why this permission was granted",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_roles",
                        to="accounts.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permission",
                "verbose_name_plural": "Role Permissions",
                "db_table": "role_permission",
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                help_text="Permissions assigned to this role",
                related_name="roles",
                through="accounts.RolePermission",
                to="accounts.permission",
            ),
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.CharField(
                        blank=True,
                        help_text="User who assigned this role",
                        max_length=200,
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Role valid from this date",
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Role valid until this date (null = indefinite)",
                        null=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the user's primary role",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this role assignment"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_users",
                        to="accounts.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "db_table": "user_role",
                "unique_together": {("user", "role")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                help_text="Roles assigned to this user",
                related_name="users",
                through="accounts.UserRole",
                to="accounts.role",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "username",
                    models.CharField(
                        help_text="Username at time of action (preserved even if user deleted)",
                        max_length=200,
                    ),
                ),
                (
                    "user_full_name",
                    models.CharField(
                        blank=True,
                        help_text="User's full name at time of action",
                        max_length=300,
                    ),
                ),
                (
                    "user_employee_id",
                    models.CharField(
                        blank=True,
                        help_text="Employee ID at time of action",
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("READ", "Read"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("SUBMIT", "Submit"),
                            ("CANCEL", "Cancel"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("PASSWORD_CHANGE", "Password Change"),
                            ("PERMISSION_GRANTED", "Permission Granted"),
                            ("PERMISSION_REVOKED", "Permission Revoked"),
                            ("EXPORT", "Export"),
                            ("IMPORT", "Import"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("USER", "User Level"),
                            ("APPLICATION", "Application Level"),
                            ("SYSTEM", "System Level"),
                        ],
                        db_index=True,
                        default="USER",
                        help_text="Level of audit (user/application/system)",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        db_index=True,
                        help_text="Category of the action (e.g., 'order', 'portfolio', 'user')",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of the action"
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of object affected (model name)",
                        max_length=100,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the affected object",
                        max_length=255,
                    ),
                ),
                (
                    "object_repr",
                    models.TextField(
                        blank=True, help_text="String representation of the object"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Details of changes made (before/after values)",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the request", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="Browser user agent string"),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True,
                        help_text="HTTP request method (GET, POST, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True, help_text="URL path of the request", max_length=500
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether the action succeeded"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if action failed"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata as JSON",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "user"],
                        name="audit_log_timesta_697639_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="audit_log_action_cf8063_idx",
                    ),
                    models.Index(
                        fields=["category", "-timestamp"],
                        name="audit_log_categor_e8011f_idx",
                    ),
                    models.Index(
                        fields=["level", "-timestamp"],
                        name="audit_log_level_4d239f_idx",
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="audit_log_object__8ccc11_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["employee_id"], name="user_employe_fbc9a5_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["employment_status"], name="user_employm_245905_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["department"], name="user_departm_4f2500_idx"),
        ),
    ]
