# Generated by Django 5.2.9 on 2025-12-12 22:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("reference_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "portfolio_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "portfolio_group",
                    models.CharField(
                        blank=True,
                        help_text="From UDF: PORTFOLIO.GROUP (e.g., Equity, Fixed Income)",
                        max_length=50,
                    ),
                ),
                (
                    "portfolio_subgroup",
                    models.CharField(
                        blank=True,
                        help_text="From UDF: PORTFOLIO.SUBGROUP",
                        max_length=50,
                    ),
                ),
                (
                    "portfolio_manager",
                    models.CharField(
                        blank=True,
                        help_text="From UDF: PORTFOLIO.MANAGER",
                        max_length=50,
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        blank=True,
                        help_text="From UDF: PORTFOLIO.STRATEGY",
                        max_length=50,
                    ),
                ),
                (
                    "initial_capital",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "current_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("base_currency", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("ACTIVE", "Active"),
                            ("REJECTED", "Rejected"),
                            ("SUSPENDED", "Suspended"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "created_by_name",
                    models.CharField(
                        editable=False,
                        help_text="Real name of maker (auto-filled)",
                        max_length=300,
                    ),
                ),
                (
                    "created_by_employee_id",
                    models.CharField(blank=True, editable=False, max_length=50),
                ),
                (
                    "approved_by_name",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Real name of checker (auto-filled)",
                        max_length=300,
                    ),
                ),
                (
                    "approved_by_employee_id",
                    models.CharField(blank=True, editable=False, max_length=50),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Checker - User who approved this portfolio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolios",
                        to="reference_data.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Maker - User who created this portfolio",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "portfolio",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "average_buy_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "last_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Latest market price", max_digits=12
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holdings",
                        to="orders.stock",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "holding",
                "ordering": ["portfolio", "stock"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("average_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("market_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "realized_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("snapshot_date", models.DateField(db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="portfolio.portfolio",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="orders.stock",
                    ),
                ),
            ],
            options={
                "db_table": "position",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                            ("DIVIDEND", "Dividend"),
                            ("INTEREST", "Interest"),
                            ("FEE", "Fee"),
                            ("BUY", "Buy"),
                            ("SELL", "Sell"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference to order/trade ID",
                        max_length=100,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "transaction_date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="portfolio.portfolio",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_transactions",
                        to="orders.stock",
                    ),
                ),
            ],
            options={
                "db_table": "transaction",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(
                fields=["owner", "status"], name="portfolio_owner_i_1ee6d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(
                fields=["portfolio_group", "status"],
                name="portfolio_portfol_feefbd_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="holding",
            unique_together={("portfolio", "stock")},
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["portfolio", "-snapshot_date"],
                name="position_portfol_357b2f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="position",
            unique_together={("portfolio", "stock", "snapshot_date")},
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["portfolio", "-transaction_date"],
                name="transaction_portfol_269674_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type", "-transaction_date"],
                name="transaction_transac_730414_idx",
            ),
        ),
    ]
