# Generated by Django 5.2.9 on 2025-12-17 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field_name",
                    models.CharField(
                        help_text="Unique field name (e.g., risk_rating, compliance_status)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label for the field", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("NUMBER", "Number"),
                            ("DATE", "Date"),
                            ("DATETIME", "Date Time"),
                            ("BOOLEAN", "Boolean"),
                            ("DROPDOWN", "Dropdown"),
                            ("MULTI_SELECT", "Multi Select"),
                            ("CURRENCY", "Currency"),
                            ("PERCENTAGE", "Percentage"),
                        ],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("PORTFOLIO", "Portfolio"),
                            ("TRADE", "Trade"),
                            ("POSITION", "Position"),
                            ("COUNTERPARTY", "Counterparty"),
                        ],
                        default="PORTFOLIO",
                        help_text="Entity this field applies to",
                        max_length=50,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("is_unique", models.BooleanField(default=False)),
                ("default_value", models.TextField(blank=True, null=True)),
                (
                    "dropdown_options",
                    models.JSONField(
                        blank=True,
                        help_text="JSON array of dropdown options, e.g., ['High', 'Medium', 'Low']",
                        null=True,
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("max_length", models.IntegerField(blank=True, null=True)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "group_name",
                    models.CharField(
                        blank=True,
                        help_text="Group related fields together",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User-Defined Field",
                "verbose_name_plural": "User-Defined Fields",
                "db_table": "udf",
                "ordering": ["entity_type", "display_order", "field_name"],
            },
        ),
        migrations.CreateModel(
            name="UDFValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_type", models.CharField(max_length=50)),
                (
                    "entity_id",
                    models.IntegerField(help_text="ID of the related entity"),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                (
                    "value_number",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("value_date", models.DateField(blank=True, null=True)),
                ("value_datetime", models.DateTimeField(blank=True, null=True)),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                ("value_json", models.JSONField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "udf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="udf.udf",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "UDF Value",
                "verbose_name_plural": "UDF Values",
                "db_table": "udf_value",
            },
        ),
        migrations.CreateModel(
            name="UDFHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="udf_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "udf_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="udf.udfvalue",
                    ),
                ),
            ],
            options={
                "verbose_name": "UDF History",
                "verbose_name_plural": "UDF Histories",
                "db_table": "udf_history",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="udf",
            index=models.Index(
                fields=["entity_type", "is_active"], name="udf_entity__55daf7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="udf",
            index=models.Index(fields=["field_name"], name="udf_field_n_8d694a_idx"),
        ),
        migrations.AddIndex(
            model_name="udfvalue",
            index=models.Index(
                fields=["entity_type", "entity_id"], name="udf_value_entity__7cba33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="udfvalue",
            index=models.Index(
                fields=["udf", "entity_type"], name="udf_value_udf_id_5e2ba7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="udfvalue",
            unique_together={("udf", "entity_type", "entity_id")},
        ),
    ]
