# Generated by Django 5.2.9 on 2025-12-12 14:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UDFType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for UDF type (e.g., 'PORTFOLIO', 'TRADE')",
                        max_length=50,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the UDF type", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of this UDF type"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this UDF type is active"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order for displaying in lists"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "UDF Type",
                "verbose_name_plural": "UDF Types",
                "db_table": "udf_type",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UDFSubtype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for UDF subtype (e.g., 'GROUP', 'MANAGER')",
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the UDF subtype", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of this UDF subtype"
                    ),
                ),
                (
                    "field_label",
                    models.CharField(
                        help_text="Label to display on forms (e.g., 'Portfolio Group')",
                        max_length=100,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, help_text="Whether this field is required"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this UDF subtype is active"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order for displaying in lists"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "udf_type",
                    models.ForeignKey(
                        help_text="Parent UDF type",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtypes",
                        to="udf.udftype",
                    ),
                ),
            ],
            options={
                "verbose_name": "UDF Subtype",
                "verbose_name_plural": "UDF Subtypes",
                "db_table": "udf_subtype",
                "ordering": ["udf_type", "display_order", "name"],
                "unique_together": {("udf_type", "code")},
            },
        ),
        migrations.CreateModel(
            name="UDFField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the field value",
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Display value shown to users", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional description or notes"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this field value is active/available",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Whether this is the default selection"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order for displaying in dropdown lists"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata as JSON",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="User who created this field",
                        max_length=100,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="User who last updated this field",
                        max_length=100,
                    ),
                ),
                (
                    "udf_subtype",
                    models.ForeignKey(
                        help_text="Parent UDF subtype",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="udf.udfsubtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "UDF Field",
                "verbose_name_plural": "UDF Fields",
                "db_table": "udf_field",
                "ordering": ["udf_subtype", "display_order", "value"],
                "indexes": [
                    models.Index(
                        fields=["udf_subtype", "is_active"],
                        name="udf_field_udf_sub_19b635_idx",
                    ),
                    models.Index(
                        fields=["is_default"], name="udf_field_is_defa_6d180c_idx"
                    ),
                ],
                "unique_together": {("udf_subtype", "code")},
            },
        ),
    ]
