# Generated by Django 5.2.9 on 2025-12-12 22:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "report_type",
                    models.CharField(
                        help_text="From UDF: REPORT.TYPE (e.g., PORTFOLIO_SUMMARY, TRADE_HISTORY, PNL_STATEMENT)",
                        max_length=50,
                    ),
                ),
                (
                    "report_category",
                    models.CharField(
                        blank=True,
                        help_text="From UDF: REPORT.CATEGORY (e.g., DAILY, WEEKLY, MONTHLY, ANNUAL)",
                        max_length=50,
                    ),
                ),
                (
                    "report_format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("EXCEL", "Excel"),
                            ("CSV", "CSV"),
                            ("JSON", "JSON"),
                        ],
                        default="PDF",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional report parameters as JSON",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("GENERATING", "Generating"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, help_text="Path to generated file", max_length=500
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "requested_by_name",
                    models.CharField(
                        editable=False,
                        help_text="Real name of requester (auto-filled)",
                        max_length=300,
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "report",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["requested_by", "status"],
                        name="report_request_24f819_idx",
                    ),
                    models.Index(
                        fields=["report_type", "-created_at"],
                        name="report_report__6dcdbd_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="report_status_9e629c_idx",
                    ),
                ],
            },
        ),
    ]
