# Generated by Django 5.2.9 on 2025-12-17 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique portfolio code", max_length=50, unique=True
                    ),
                ),
                ("name", models.CharField(help_text="Portfolio name", max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "currency",
                    models.CharField(
                        help_text="Base currency (e.g., USD, SGD)", max_length=3
                    ),
                ),
                (
                    "manager",
                    models.CharField(
                        blank=True, help_text="Portfolio manager", max_length=200
                    ),
                ),
                ("portfolio_client", models.CharField(blank=True, max_length=200)),
                (
                    "cash_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current cash balance",
                        max_digits=20,
                    ),
                ),
                ("cash_balance_list", models.CharField(blank=True, max_length=200)),
                ("cost_centre_code", models.CharField(blank=True, max_length=50)),
                ("corp_code", models.CharField(blank=True, max_length=50)),
                ("account_group", models.CharField(blank=True, max_length=100)),
                ("portfolio_group", models.CharField(blank=True, max_length=100)),
                ("report_group", models.CharField(blank=True, max_length=100)),
                ("entity_group", models.CharField(blank=True, max_length=100)),
                ("revaluation_status", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("ACTIVE", "Active"),
                            ("REJECTED", "Rejected"),
                            ("INACTIVE", "Inactive"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "submitted_for_approval_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_comments", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolios_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolios_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio",
                "verbose_name_plural": "Portfolios",
                "db_table": "portfolio",
                "ordering": ["-created_at"],
                "permissions": [
                    ("approve_portfolio", "Can approve portfolio"),
                    ("reject_portfolio", "Can reject portfolio"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PortfolioHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("SUBMIT", "Submitted for Approval"),
                            ("APPROVE", "Approved"),
                            ("REJECT", "Rejected"),
                            ("ACTIVATE", "Activated"),
                            ("DEACTIVATE", "Deactivated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                ("changes", models.JSONField(default=dict)),
                ("comments", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_history_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="portfolio.portfolio",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio History",
                "verbose_name_plural": "Portfolio Histories",
                "db_table": "portfolio_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(fields=["code"], name="portfolio_code_99ac76_idx"),
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(
                fields=["status", "is_active"], name="portfolio_status_d756d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(
                fields=["currency"], name="portfolio_currenc_a66054_idx"
            ),
        ),
    ]
