# Generated by Django 5.2.9 on 2025-12-17 23:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="ISO country code",
                        max_length=3,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("continent", models.CharField(blank=True, max_length=50)),
                ("currency_code", models.CharField(blank=True, max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("source_system", models.CharField(blank=True, max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=100)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "db_table": "reference_country",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 4217 currency code (e.g., USD, EUR, SGD)",
                        max_length=3,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Must be 3 uppercase letters"
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(help_text="Currency name", max_length=100)),
                ("full_name", models.CharField(blank=True, max_length=200)),
                (
                    "symbol",
                    models.CharField(
                        blank=True, help_text="Currency symbol", max_length=10
                    ),
                ),
                ("decimal_places", models.IntegerField(default=2)),
                ("rate_precision", models.IntegerField(default=6)),
                ("calendar", models.CharField(blank=True, max_length=50)),
                ("spot_schedule", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("is_base_currency", models.BooleanField(default=False)),
                ("source_system", models.CharField(blank=True, max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=100)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "db_table": "reference_currency",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("calendar_label", models.CharField(db_index=True, max_length=50)),
                ("calendar_description", models.CharField(blank=True, max_length=200)),
                ("holiday_date", models.DateField(db_index=True)),
                ("holiday_name", models.CharField(blank=True, max_length=200)),
                (
                    "holiday_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PUBLIC", "Public Holiday"),
                            ("TRADING", "Trading Holiday"),
                            ("SETTLEMENT", "Settlement Holiday"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_trading_day", models.BooleanField(default=True)),
                ("is_settlement_day", models.BooleanField(default=True)),
                ("market_open_time", models.TimeField(blank=True, null=True)),
                ("market_close_time", models.TimeField(blank=True, null=True)),
                ("is_half_day", models.BooleanField(default=False)),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("SGX", "Singapore Exchange"),
                            ("NYSE", "New York Stock Exchange"),
                            ("NASDAQ", "NASDAQ"),
                            ("LSE", "London Stock Exchange"),
                            ("HKEX", "Hong Kong Exchange"),
                        ],
                        default="SGX",
                        max_length=50,
                    ),
                ),
                ("source_system", models.CharField(blank=True, max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=100)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trading Calendar",
                "verbose_name_plural": "Trading Calendars",
                "db_table": "reference_calendar",
                "ordering": ["-holiday_date"],
                "indexes": [
                    models.Index(
                        fields=["holiday_date", "exchange"],
                        name="reference_c_holiday_968e8b_idx",
                    )
                ],
                "unique_together": {("calendar_label", "holiday_date")},
            },
        ),
        migrations.CreateModel(
            name="Counterparty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique counterparty code",
                        max_length=50,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("legal_name", models.CharField(blank=True, max_length=300)),
                ("short_name", models.CharField(blank=True, max_length=100)),
                (
                    "counterparty_type",
                    models.CharField(
                        choices=[
                            ("BANK", "Bank"),
                            ("BROKER", "Broker"),
                            ("CORPORATE", "Corporate"),
                            ("INDIVIDUAL", "Individual"),
                            ("INSTITUTIONAL", "Institutional"),
                            ("GOVERNMENT", "Government"),
                        ],
                        default="CORPORATE",
                        max_length=50,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("tax_id", models.CharField(blank=True, max_length=50)),
                ("registration_number", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended"),
                            ("CLOSED", "Closed"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "risk_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("credit_rating", models.CharField(blank=True, max_length=20)),
                ("source_system", models.CharField(blank=True, max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=100)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Counterparty",
                "verbose_name_plural": "Counterparties",
                "db_table": "reference_counterparty",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="reference_c_code_5997a4_idx"),
                    models.Index(
                        fields=["counterparty_type", "status"],
                        name="reference_c_counter_63157f_idx",
                    ),
                ],
            },
        ),
    ]
