# Generated by Django 5.2.9 on 2026-05-31 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FXRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency_pair",
                    models.CharField(
                        db_index=True,
                        help_text="Currency pair (e.g., USD/EUR, GBP/USD)",
                        max_length=10,
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        db_index=True,
                        help_text="Base currency code (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "quote_currency",
                    models.CharField(
                        db_index=True,
                        help_text="Quote currency code (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Exchange rate (up to 10 decimal places)",
                        max_digits=20,
                    ),
                ),
                (
                    "bid_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="Bid rate (buy price)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "ask_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="Ask rate (sell price)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "mid_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="Mid rate ((bid + ask) / 2)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "rate_date",
                    models.DateField(db_index=True, help_text="Date of the rate"),
                ),
                (
                    "rate_time",
                    models.DateTimeField(
                        db_index=True, help_text="Timestamp of the rate"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("BLOOMBERG", "Bloomberg"),
                            ("REUTERS", "Reuters"),
                            ("MANUAL", "Manual Entry"),
                            ("API", "API Feed"),
                            ("HIVE", "Hive Import"),
                        ],
                        db_index=True,
                        default="MANUAL",
                        help_text="Source of the rate",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this rate is currently active",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FX Rate",
                "verbose_name_plural": "FX Rates",
                "db_table": "market_data_fx_rate",
                "ordering": ["-rate_date", "-rate_time"],
                "indexes": [
                    models.Index(
                        fields=["currency_pair", "-rate_date"],
                        name="market_data_currenc_4d19a8_idx",
                    ),
                    models.Index(
                        fields=["base_currency", "quote_currency"],
                        name="market_data_base_cu_9001d9_idx",
                    ),
                    models.Index(
                        fields=["rate_date", "is_active"],
                        name="market_data_rate_da_ccd5b2_idx",
                    ),
                    models.Index(
                        fields=["source", "-rate_time"],
                        name="market_data_source_6b92d4_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("currency_pair", "rate_date", "rate_time", "source"),
                        name="unique_fx_rate_per_source",
                    )
                ],
            },
        ),
    ]
